name: Deploy OpenVPN Server

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  OVPN_SERVER_IP: ${{ secrets.OVPN_SERVER_IP }}
  SSH_USER: ${{ secrets.SSH_USER }}
  SSH_PORT: ${{ secrets.SSH_PORT || '22' }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy OpenVPN Server via SSH
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ env.OVPN_SERVER_IP }}
        username: ${{ env.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ env.SSH_PORT }}
        script: |
          docker pull linuxserver/openvpn-as
          docker run -d \
            --name=openvpn-as \
            --cap-add=NET_ADMIN \
            -e PUID=1000 \
            -e PGID=1000 \
            -e TZ=Etc/UTC \
            -e INTERFACE=eth0 \
            -e ADMIN_PASSWORD=${{ secrets.OVPN_ADMIN_PASSWORD }} \
            -p 943:943 \
            -p 9443:9443 \
            -p 1194:1194/udp \
            -v /var/lib/docker-volumes/openvpn-as/config:/config \
            --restart unless-stopped \
            linuxserver/openvpn-as
