name: OpenVPN Server

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-vpn:
    runs-on: ubuntu-latest
    steps:
      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn easy-rsa

      - name: Set Up OpenVPN Server
        run: |
          make-cadir ~/openvpn-ca
          cd ~/openvpn-ca
          source vars
          ./clean-all
          ./build-ca --batch
          ./build-key-server --batch server
          ./build-dh
          openvpn --genkey --secret keys/ta.key
          cp keys/{ca.crt,server.crt,server.key,dh2048.pem,ta.key} /etc/openvpn/
          echo 'port 1194
proto udp
dev tun
ca ca.crt
cert server.crt
key server.key
dh dh2048.pem
auth SHA256
cipher AES-256-CBC
persist-key
persist-tun
status openvpn-status.log
verb 3' > /etc/openvpn/server.conf

      - name: Start OpenVPN Server
        run: |
          sudo systemctl start openvpn@server
          sudo systemctl enable openvpn@server
          echo "OpenVPN server started on GitHub Actions!"

      - name: Output Server Info
        run: |
          echo "Server IP: $(curl -s ifconfig.me)"
          echo "Port: 1194"
          echo "Protocol: UDP"
